set_property IOSTANDARD LVCMOS25 [get_ports {wbt_led_o[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {wbt_led_o[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports przycisk]
set_property IOSTANDARD LVCMOS15 [get_ports led]
set_property PACKAGE_PIN Y21 [get_ports {wbt_led_o[1]}]
set_property PACKAGE_PIN W21 [get_ports {wbt_led_o[0]}]
set_property PACKAGE_PIN AK25 [get_ports przycisk]
set_property PACKAGE_PIN G2 [get_ports led]



set_property IOSTANDARD LVDS_25 [get_ports {CLK0_OUT_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {CLK1_OUT_P[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {CLK2_OUT_P[0]}]
set_property PACKAGE_PIN AG17 [get_ports {CLK0_OUT_P[0]}]
set_property PACKAGE_PIN AE13 [get_ports {CLK1_OUT_P[0]}]
set_property PACKAGE_PIN AC28 [get_ports {CLK2_OUT_P[0]}]



set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {DAC_DAT_P[0]}]
set_property PACKAGE_PIN AB15 [get_ports {DAC_DAT_P[0]}]
set_property PACKAGE_PIN AE18 [get_ports {DAC_DAT_P[1]}]
set_property PACKAGE_PIN AH17 [get_ports {DAC_DAT_P[2]}]
set_property PACKAGE_PIN AJ16 [get_ports {DAC_DAT_P[3]}]
set_property PACKAGE_PIN AD16 [get_ports {DAC_DAT_P[4]}]
set_property PACKAGE_PIN AH14 [get_ports {DAC_DAT_P[5]}]
set_property PACKAGE_PIN AA15 [get_ports {DAC_DAT_P[6]}]
set_property PACKAGE_PIN AD14 [get_ports {DAC_DAT_P[7]}]
set_property PACKAGE_PIN AE16 [get_ports {DAC_DAT_P[8]}]
set_property PACKAGE_PIN AJ15 [get_ports {DAC_DAT_P[9]}]
set_property PACKAGE_PIN AG12 [get_ports {DAC_DAT_P[10]}]
set_property PACKAGE_PIN AE12 [get_ports {DAC_DAT_P[11]}]
set_property PACKAGE_PIN AB12 [get_ports {DAC_DAT_P[12]}]
set_property PACKAGE_PIN AF15 [get_ports {DAC_DAT_P[13]}]





set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[17]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[16]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {IBUF_DS_P[0]}]
set_property PACKAGE_PIN AE27 [get_ports {IBUF_DS_P[0]}]


set_property IOSTANDARD LVCMOS25 [get_ports {save[39]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[38]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[37]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[36]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[35]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[34]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[33]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[32]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[31]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[30]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[29]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[28]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[27]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[26]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[25]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[24]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[23]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[22]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[21]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[20]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[19]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[18]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[17]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[16]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {save[0]}]
set_property PACKAGE_PIN AH27 [get_ports {save[38]}]
set_property PACKAGE_PIN AD25 [get_ports {save[33]}]
set_property PACKAGE_PIN AE26 [get_ports {save[32]}]
set_property PACKAGE_PIN AB29 [get_ports {save[31]}]
set_property PACKAGE_PIN AB30 [get_ports {save[30]}]
set_property PACKAGE_PIN Y26 [get_ports {save[29]}]
set_property PACKAGE_PIN Y27 [get_ports {save[28]}]
set_property PACKAGE_PIN AG26 [get_ports {save[27]}]
set_property PACKAGE_PIN AG27 [get_ports {save[26]}]
set_property PACKAGE_PIN AE25 [get_ports {save[21]}]
set_property PACKAGE_PIN AF25 [get_ports {save[20]}]
set_property PACKAGE_PIN AC29 [get_ports {save[19]}]
set_property PACKAGE_PIN AD29 [get_ports {save[18]}]
set_property PACKAGE_PIN Y30 [get_ports {save[17]}]
set_property PACKAGE_PIN AA30 [get_ports {save[16]}]
set_property PACKAGE_PIN AC27 [get_ports {save[14]}]
set_property PACKAGE_PIN AJ26 [get_ports {save[13]}]
set_property PACKAGE_PIN AK30 [get_ports {save[10]}]
set_property PACKAGE_PIN AC14 [get_ports {save[9]}]
set_property PACKAGE_PIN AC13 [get_ports {save[8]}]
set_property PACKAGE_PIN AF18 [get_ports {save[7]}]

set_property PACKAGE_PIN AF17 [get_ports {PLL1_SYNCB[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PLL1_SYNCB[0]}]

set_property PACKAGE_PIN AK28 [get_ports spi_mosi_ad95xx_o]
set_property PACKAGE_PIN AH28 [get_ports spi_miso_i_1]
set_property PACKAGE_PIN AK27 [get_ports spi_sclk_ad95xx_o]
set_property PACKAGE_PIN AB27 [get_ports wbt_spi_cs_ad9510_o]
set_property PACKAGE_PIN AJ30 [get_ports wbt_spi_cs_ad9516_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi_miso_i_1]
set_property IOSTANDARD LVCMOS25 [get_ports spi_mosi_ad95xx_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi_sclk_ad95xx_o]
set_property IOSTANDARD LVCMOS25 [get_ports wbt_spi_cs_ad9510_o]
set_property IOSTANDARD LVCMOS25 [get_ports wbt_spi_cs_ad9516_o]

set_property PACKAGE_PIN AJ29 [get_ports wbt_adf4002_le_o]
set_property IOSTANDARD LVCMOS25 [get_ports wbt_adf4002_le_o]

set_property PACKAGE_PIN AH29 [get_ports wbt_pll2_reset_n_o]
set_property IOSTANDARD LVCMOS25 [get_ports wbt_pll2_reset_n_o]

set_property PACKAGE_PIN AK26 [get_ports PD_CLK]
set_property IOSTANDARD LVCMOS25 [get_ports PD_CLK]
set_property PACKAGE_PIN AJ28 [get_ports PD_DATA]
set_property IOSTANDARD LVCMOS25 [get_ports PD_DATA]

set_property PACKAGE_PIN AG29 [get_ports wbt_spi_adc_sdi_o]
set_property IOSTANDARD LVCMOS25 [get_ports wbt_spi_adc_sdi_o]
set_property PACKAGE_PIN AF29 [get_ports wbt_spi_adc_cnv_o]
set_property IOSTANDARD LVCMOS25 [get_ports wbt_spi_adc_cnv_o]
set_property PACKAGE_PIN AG30 [get_ports spi_sclk_o]
set_property IOSTANDARD LVCMOS25 [get_ports spi_sclk_o]
set_property PACKAGE_PIN AF30 [get_ports spi_miso_i]
set_property IOSTANDARD LVCMOS25 [get_ports spi_miso_i]
